<a href="https://colab.research.google.com/github/2estherblaise-max/ECON3916-Statical-Machine-Learning./blob/main/Lab13ipynb_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt

# Step 1: Ingestion and Naive Model
url = 'https://raw.githubusercontent.com/2estherblaise-max/ECON3916-Statical-Machine-Learning./refs/heads/main/Data/Zillow_California_2026_Hedonic.csv'
df = pd.read_csv(url)
df

     Property_Age  Distance_to_Tech_Hub  Sale_Price
0            77.5                  38.1   684100.56
1            11.0                  95.1   413634.22
2            47.7                  73.5   456709.35
3            61.9                  60.3   624533.95
4           100.8                  16.4   870137.54
..            ...                   ...         ...
995          87.7                  10.1   932592.35
996          21.2                  91.8   412741.12
997          96.5                  14.5   880901.56
998          20.1                  95.1   396659.79
999          62.4                  45.2   733067.74

[1000 rows x 3 columns]

In [27]:
naive_model = smf.ols("Sale_Price ~ Property_Age",data=df).fit()
print(naive_model.summary())
print("\nNaive Age Coefficient:", naive_model.params['Property_Age'])

                            OLS Regression Results
==============================================================================
Dep. Variable:             Sale_Price   R-squared:                       0.757
Model:                            OLS   Adj. R-squared:                  0.757
Method:                 Least Squares   F-statistic:                     3105.
Date:                Wed, 18 Mar 2026   Prob (F-statistic):          1.26e-308
Time:                        20:09:10   Log-Likelihood:                -12818.
No. Observations:                1000   AIC:                         2.564e+04
Df Residuals:                     998   BIC:                         2.565e+04
Df Model:                           1
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept     3.013e+05   7218.570     41.742      0.000    2.87e+05    3.15e+05
Property_Age  5573.6306    100.027     55.721      0.000    5377.343    5769.919
==============================================================================
Omnibus:                        2.623   Durbin-Watson:                   2.019
Prob(Omnibus):                  0.269   Jarque-Bera (JB):                2.313
Skew:                          -0.019   Prob(JB):                        0.315
Kurtosis:                       2.767   Cond. No.                         184.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Naive Age Coefficient: 5573.630595439929

In [28]:
# Step 2: The Multivariate Model
multi_model = smf.ols('Sale_Price ~ Property_Age + Distance_to_Tech_Hub', data=df).fit()
print(multi_model.summary())
print("\nMultivariate Age Coefficient:", multi_model.params['Property_Age'])

                            OLS Regression Results
==============================================================================
Dep. Variable:             Sale_Price   R-squared:                       0.954
Model:                            OLS   Adj. R-squared:                  0.954
Method:                 Least Squares   F-statistic:                 1.040e+04
Date:                Wed, 18 Mar 2026   Prob (F-statistic):               0.00
Time:                        20:09:10   Log-Likelihood:                -11982.
No. Observations:                1000   AIC:                         2.397e+04
Df Residuals:                     997   BIC:                         2.399e+04
Df Model:                           2
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept             1.203e+06   1.41e+04     85.371      0.000    1.18e+06    1.23e+06
Property_Age         -2063.1292    124.190    -16.613      0.000   -2306.833   -1819.426
Distance_to_Tech_Hub -7964.2448    121.354    -65.628      0.000   -8202.383   -7726.107
==============================================================================
Omnibus:                        0.379   Durbin-Watson:                   2.053
Prob(Omnibus):                  0.827   Jarque-Bera (JB):                0.266
Skew:                           0.002   Prob(JB):                        0.876
Kurtosis:                       3.080   Cond. No.                         959.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Multivariate Age Coefficient: -2063.1292168021246

In [29]:
df

     Property_Age  Distance_to_Tech_Hub  Sale_Price
0            77.5                  38.1   684100.56
1            11.0                  95.1   413634.22
2            47.7                  73.5   456709.35
3            61.9                  60.3   624533.95
4           100.8                  16.4   870137.54
..            ...                   ...         ...
995          87.7                  10.1   932592.35
996          21.2                  91.8   412741.12
997          96.5                  14.5   880901.56
998          20.1                  95.1   396659.79
999          62.4                  45.2   733067.74

[1000 rows x 3 columns]

In [30]:
# Step 3: FWL Theorem Manual Proof
# 3a: Partial out distance from Price
res_y_model = smf.ols('Sale_Price ~ Distance_to_Tech_Hub', data=df).fit()
df['Price_Residuals'] = res_y_model.resid

In [31]:
# 3b: Partial out distance from Age
res_x_model = smf.ols('Property_Age ~ Distance_to_Tech_Hub', data=df).fit()
df['Age_Residuals'] = res_x_model.resid

In [32]:
# 3c: Regress Residuals on Residuals (-1 removes the intercept for exact mathematical matching)
fwl_model = smf.ols('Price_Residuals ~ Age_Residuals', data=df).fit()
print("\nFWL Isolated Age Coefficient:", fwl_model.params['Age_Residuals'])

FWL Isolated Age Coefficient: -2063.129216802138

In [33]:
res_y_model